from __future__ import annotations

import os
from typing import List


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


APP_TITLE = "Tetris"

MIN_WINDOW_WIDTH = 350
MIN_WINDOW_HEIGHT = 700
DEFAULT_WINDOW_WIDTH = 425
DEFAULT_WINDOW_HEIGHT = 850
MAX_WINDOW_WIDTH_RATIO = 0.55
MAX_WINDOW_HEIGHT_RATIO = 0.90
WINDOW_WIDTH = DEFAULT_WINDOW_WIDTH
WINDOW_HEIGHT = DEFAULT_WINDOW_HEIGHT
ROWS = 20
COLS = 10
BOARD_MIN_BLOCK_SIZE = 17
BOARD_MAX_WIDTH_RATIO = 0.92
BOARD_MAX_HEIGHT_RATIO = 0.86
BOARD_SIDE_PADDING_RATIO = 0.06
UI_SCALE_MIN = 0.92
UI_SCALE_MAX = 1.35
FONT_SCALE_BASE_HEIGHT = 700
CONTENT_MAX_WIDTH = 620
FORM_MAX_WIDTH = 520
TABLE_MAX_WIDTH = 760
PROFILE_PANEL_MAX_WIDTH = 620
LEADERBOARD_PANEL_MAX_WIDTH = 780
HISTORY_PANEL_MAX_WIDTH = 760
SETTINGS_PANEL_MAX_WIDTH = 620
SEASON1_PANEL_MAX_WIDTH = 700
RESPONSIVE_PANEL_WIDTH_RATIO = 0.86
BLOCK_SIZE = MIN_WINDOW_WIDTH // COLS
FPS = 60

WHITE = (255, 255, 255)
GRAY = (50, 50, 50)
BLUE = (0, 150, 255)
RED = (255, 0, 0)
DARK_RED = (115, 0, 0)
BLACK = (0, 0, 0)
GOLD = (255, 215, 0)
SILVER = (192, 192, 192)
BRONZE = (205, 127, 50)
SOFT_BLACK = (12, 13, 18)
PANEL_BG = (22, 24, 32)
PANEL_BORDER = (82, 88, 102)
MUTED_TEXT = (155, 161, 174)
BUTTON_BG = (34, 38, 50)
BUTTON_HOVER_BG = (58, 64, 82)
BUTTON_SELECTED_BG = (112, 30, 38)
BUTTON_BORDER = (118, 124, 140)

ASSET_MENU_MUSIC = "assets/audio/music/menu-music.mp3"
ASSET_GAME_MUSIC = "assets/audio/music/game-music.mp3"
ASSET_BACKGROUND = "assets/images/background.png"
ASSET_FIRST_PAGE = "assets/images/first_page.png"

BASE_MAX_VOLUME = 0.07
DEFAULT_VOLUME_PERCENT = 100
DEFAULT_MUSIC_ENABLED = True
MAX_PLAYER_NAME_LENGTH = 12
BUTTON_DEBOUNCE_MS = 180
TETRIS_BACKEND_URL = os.getenv("TETRIS_BACKEND_URL", "https://tetris-project-ahgg.onrender.com").rstrip("/")
CURRENT_SEASON = 2
ARCHIVED_SEASON = 1

KEY_REPEAT_INITIAL_DELAY_MS = 140
KEY_REPEAT_MOVE_INTERVAL_MS = 45
KEY_REPEAT_SOFT_DROP_INTERVAL_MS = 35

SCORE_EFFECTS_ENABLED = True
SCORE_POPUP_DURATION_MS = 850
SCORE_POPUP_RISE_PIXELS = 48
SCORE_POPUP_FONT_SIZE = 26
SCORE_POPUP_LINE_CLEAR_FONT_SIZE = 30
SCORE_POPUP_MAX_ACTIVE = 6
SCORE_POPUP_COLOR = WHITE
SCORE_POPUP_LINE_CLEAR_COLOR = GOLD
SCORE_POPUP_COMBO_COLOR = RED
BOARD_FLASH_DURATION_MS = 280
BOARD_FLASH_MAX_ALPHA = 120
BOARD_FLASH_WIDTH = 5
BOARD_FLASH_COLOR = GOLD
SCORE_PULSE_DURATION_MS = 260
SCORE_PULSE_SCALE = 1.25
COMBO_WINDOW_MS = 1800
COMBO_DISPLAY_DURATION_MS = 950
HARD_DROP_SCORE_PER_ROW = 2

MENU_TITLE_FONT_SIZE = 44
MENU_SEASON_TITLE_FONT_SIZE = 40
MENU_BUTTON_FONT_SIZE = 24
MENU_BUTTON_WIDTH = 230
MENU_BUTTON_HEIGHT = 42
MENU_BUTTON_GAP = 12
MENU_TOP_Y = 70
MENU_SELECTED_SCALE = 1.04
MENU_PRIMARY_TEXT_COLOR = WHITE
MENU_SECONDARY_TEXT_COLOR = MUTED_TEXT
MENU_BUTTON_BG_COLOR = BUTTON_BG
MENU_BUTTON_HOVER_COLOR = BUTTON_HOVER_BG

MODE_CARD_WIDTH = 292
MODE_CARD_HEIGHT = 76
MODE_CARD_GAP = 12
MODE_TITLE_FONT_SIZE = 34
MODE_NAME_FONT_SIZE = 24
MODE_DESCRIPTION_FONT_SIZE = 14

HUD_SCORE_FONT_SIZE = 28
HUD_SCORE_SHADOW_OFFSET = 2
HUD_SCORE_TEXT_COLOR = WHITE
HUD_SCORE_SHADOW_COLOR = BLACK
HUD_MODE_FONT_SIZE = 15

ACTIVE_PIECE_COLORS = [
    (255, 92, 92),
    (88, 190, 255),
    (111, 235, 162),
    (255, 221, 91),
    (190, 130, 255),
    (255, 154, 82),
]
LOCKED_PIECE_COLOR = DARK_RED

GOOGLE_SHEET_CSV_URL = (
    "https://docs.google.com/spreadsheets/d/1bFY8FxdE8gl1qFj3jQm7bta9Pizw_yqkSpm-CqRr2JE/"
    "export?format=csv&gid=469714189"
)
GOOGLE_FORM_URL = (
    "https://docs.google.com/forms/d/e/"
    "1FAIpQLSd1IqHQhAawskKNluN1Be9Ey2ULny0OGeUkJ2XP3aFjD0rR-Q/formResponse"
)
GOOGLE_FIELD_NAME = "entry.1969811371"
GOOGLE_FIELD_SCORE = "entry.1726351225"

NETWORK_TIMEOUT_SECONDS = 5.0
AUTH_NETWORK_TIMEOUT_SECONDS = 12.0
SCORE_NETWORK_TIMEOUT_SECONDS = 8.0
NETWORK_RETRIES = 2
NETWORK_BACKOFF_SECONDS = 0.35
REGISTER_RECOVERY_DELAY_SECONDS = 1.0
DEBUG_ONLINE_SCORE_FLOW = _env_bool("DEBUG_ONLINE_SCORE_FLOW", True)

SHEET_DATETIME_FORMAT = "%d.%m.%Y %H:%M:%S"

SHAPES = [
    [[1, 1, 1], [0, 1, 0]],  # T
    [[1, 1], [1, 1]],  # O
    [[0, 1, 1], [1, 1, 0]],  # Z
    [[1, 1, 0], [0, 1, 1]],  # S
    [[1, 1, 1, 1]],  # I
    [
        [1, 0, 1, 1, 1],  # 88
        [1, 0, 1, 0, 0],
        [1, 1, 1, 1, 1],
        [0, 0, 1, 0, 1],
        [1, 1, 1, 0, 1],
    ],
    [[1, 0], [1, 0], [1, 1]],  # L
    [[0, 1], [0, 1], [1, 1]],  # J
]
SHAPE_NAMES = ["T", "O", "Z", "S", "I", "88", "L", "J"]
SHAPE_WEIGHTS = [100, 100, 100, 100, 100, 17.5, 100, 100]

GAME_MODE_PEACEFUL = "peaceful"
GAME_MODE_EASY = "easy"
GAME_MODE_NORMAL = "normal"
GAME_MODE_HARD = "hard"
DEFAULT_GAME_MODE = GAME_MODE_NORMAL

DEFAULT_PIECE_WEIGHT = 100
PEACEFUL_EXCLUDED_PIECE = "88"
EASY_LOW_WEIGHT_PIECE = "88"
EASY_LOW_WEIGHT = 17.5
NORMAL_DOUBLE_WEIGHT_PIECE = "88"
NORMAL_DOUBLE_WEIGHT = 35
HARD_FREQUENT_PIECE = "88"
HARD_FREQUENT_WEIGHT = 100

GAME_MODE_CONFIGS = {
    GAME_MODE_PEACEFUL: {
        "label": "Peaceful",
        "description": "One configured piece is disabled.",
        "excluded_pieces": [PEACEFUL_EXCLUDED_PIECE],
        "weights": {},
    },
    GAME_MODE_EASY: {
        "label": "Easy",
        "description": "One configured piece appears rarely.",
        "excluded_pieces": [],
        "weights": {EASY_LOW_WEIGHT_PIECE: EASY_LOW_WEIGHT},
    },
    GAME_MODE_NORMAL: {
        "label": "Normal",
        "description": "One configured piece appears more often.",
        "excluded_pieces": [],
        "weights": {NORMAL_DOUBLE_WEIGHT_PIECE: NORMAL_DOUBLE_WEIGHT},
    },
    GAME_MODE_HARD: {
        "label": "Hard",
        "description": "One configured piece appears very often.",
        "excluded_pieces": [],
        "weights": {HARD_FREQUENT_PIECE: HARD_FREQUENT_WEIGHT},
    },
}
GAME_MODE_ORDER = [
    GAME_MODE_PEACEFUL,
    GAME_MODE_EASY,
    GAME_MODE_NORMAL,
    GAME_MODE_HARD,
]


def validated_shape_weights() -> List[float]:
    if len(SHAPE_WEIGHTS) == len(SHAPES):
        return SHAPE_WEIGHTS
    return [100] * len(SHAPES)


VALIDATED_SHAPE_WEIGHTS = validated_shape_weights()
